version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.14
    build:
      args:
        centos_version : "6"
        java_version : "adopt@1.14.0-0"

  test:
    image: netty:centos-6-1.14

  test-leak:
    image: netty:centos-6-1.14

  test-boringssl-static:
    image: netty:centos-6-1.14

  shell:
    image: netty:centos-6-1.14
